#!/usr/bin/env python3
"""Generate the in-app legal agreement module from the canonical Markdown documents.

Canonical sources:
  docs/legal/隐私政策.md
  docs/legal/用户服务协议.md

Generated mirror:
  miniprogram/legal/agreements.js

Run with --check in CI/check mode to fail when the mirror is stale.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "privacy": ROOT / "docs" / "legal" / "隐私政策.md",
    "terms": ROOT / "docs" / "legal" / "用户服务协议.md",
}
TARGET = ROOT / "miniprogram" / "legal" / "agreements.js"


def clean_inline(text: str) -> str:
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1（\2）", text)
    text = text.replace("**", "").replace("`", "")
    return text.strip()


def parse_markdown(path: Path) -> dict:
    lines = path.read_text(encoding="utf-8").splitlines()
    title = ""
    blocks: list[dict] = []
    paragraph: list[str] = []

    def flush_paragraph() -> None:
        nonlocal paragraph
        if paragraph:
            text = clean_inline("".join(paragraph))
            if text:
                blocks.append({"type": "paragraph", "text": text})
            paragraph = []

    for raw in lines:
        line = raw.strip()
        if not line:
            flush_paragraph()
            continue
        if line.startswith("# "):
            flush_paragraph()
            if not title:
                title = clean_inline(line[2:])
            continue
        if line.startswith("## "):
            flush_paragraph()
            blocks.append({"type": "heading", "level": 2, "text": clean_inline(line[3:])})
            continue
        if line.startswith("### "):
            flush_paragraph()
            blocks.append({"type": "heading", "level": 3, "text": clean_inline(line[4:])})
            continue
        if line.startswith("> "):
            flush_paragraph()
            text = clean_inline(line[2:])
            if text:
                blocks.append({"type": "paragraph", "text": text})
            continue
        if line.startswith("- "):
            flush_paragraph()
            blocks.append({"type": "bullet", "text": clean_inline(line[2:])})
            continue
        if re.match(r"^\d+\.\s+", line):
            flush_paragraph()
            blocks.append({"type": "paragraph", "text": clean_inline(line)})
            continue
        paragraph.append(line)

    flush_paragraph()
    if not title:
        raise ValueError(f"missing H1 title: {path}")
    return {"title": title, "blocks": blocks}


def build_module() -> str:
    data = {key: parse_markdown(path) for key, path in SOURCES.items()}
    header = (
        "/* AUTO-GENERATED by scripts/sync-legal-pages.py. Do not edit directly. */\n"
        "/* Source: docs/legal/隐私政策.md, docs/legal/用户服务协议.md */\n"
    )
    return header + "module.exports = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check whether the generated file is current")
    args = parser.parse_args()

    expected = build_module()
    if args.check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if actual != expected:
            print(f"legal agreement mirror is stale: run python3 {Path(__file__).relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("legal agreement mirror is in sync ✓")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"generated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
